### ISSUE TITLE
Feedback Datadashboard

### ISSUE THREAD

**Issue by nerdale** [GenesisMauries/cdmx-2018-06-bc-core-am-data-dashboard#23]
Queridas @GenesisMauries Queletzu y Ana:
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. Felicitaciones por no rendirse, continuar, entregar y presentar, espero que el aprendizaje sea bueno y que retomen el proyecto más adelante para que aparezca en un futuro en sus portafolios.

2. No sirve de nada crear issues si no va a existir una interacción ni se van a utilizar con el propósito que tienen, que es hacer un seguimiento de tareas y/o problemas que pueda tener el desarrollo. Deben trabajar esa parte, ya era un feedback que habían recibido.

3. Es poco lo que puedo decir en cuanto a funcionalidad del datadashboard, de todo lo que debía mostrar solo visibiliza una pequeña parte de data:  **Sedes**, **Generación**, **Estudiantes** y **Promedio**

4. Me preocupa y llama profundamente la atención errores pequeños, esenciales y básicos que no solucionaron, errores como por ejemplo: 
a) No se ve la imagen de lucile por 2 motivos, la ruta y la extensión están mal `<img id="labo" src="../src/img/lucile.png" alt="">` debería ser `<img id="labo" src="img/lucile.PNG" alt="">`
b) Tienen etiquetas que cierran pero nunca abren, como la etiqueta `</main>` en la línea 58 del **index.html**, en la línea 15 y 16 del mismo archivo tienen `<header></header>` sin contenido, o más grabe aún, en la línea 68 del mismo archivo tienen la etiqueta `</html>` cerrando pero nunca abre y es una etiqueta **elemental** para los archivos HTML.
Me parece que es un tema del que deben tomar medidas ahora ya, es preocupante no manejar esos detalles. Acerquense a los coaches si necesitan ayuda personalizada.

5. No es responsive, se ve estudio de usuario, documenten todo lo que puedan para la pŕoxima, no solo mostrar que les preguntaron a sus usuarios, sino que también una muestra de las respuestas que obtuvieron.

6. Sobre color y alineación no es mucho lo que puedo decir porque es poco lo que se puede ver.

7. Si bien utilizaron una tipografía distinta a las que vienen por defecto en los computadores, recuerden que el cliente tiene su propio manual de marca donde se especifica que colores usar, que tipografías, que fondos de color etc. Esta vez lo pasé por alto pero es un detalle que no se les puede volver a escapar.

8. Se nota el intento de trabajar con github, sigan aprendiendo y practicando, les será de gran utilidad.

Les faltó bastante trabajo, les dejo el desafío de terminarlo, quizás no hoy, pero si en un tiempo más :rocket: 
Vamos con todo en el siguiente proyecto :metal:

**Comment by GenesisMauries** [comment]
Gracias por la retroalimentacion, estamos cocientes de que el reto aun no termina.

**Comment by nerdale** [comment]
Vamos chiquillassssss con toodoooo :muscle:
