### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [GenesisMauries/cdmx-2018-06-bc-core-am-data-dashboard#6]
Hola @GenesisMauries y Compañera
He estado revisando el proyecto y tengo algunos comentarios:

1. @GenesisMauries  debes agregar como colaboradora a **alppacat**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. De la mano del punto anterior veo que no realizaron los issues y milestones correspondientes al sprint 2 del proyecto, que pasó con eso?

3. Buen trabajo y completo de investigación del usuario, se nota la dedicación e interés en saber las necesidades exactas del usuario.

4. Muy bien por las funciones que ya tienes armada la estructura inicial, se nota la visión desde los tests para aquello :clap: 

5. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

6. Les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

Vamos comiencen luego con a darle forma al datadashboard :muscle: :rocket:

**Comment by nerdale** [comment]
Daré por cerrado el issue 
:rocket:

**Comment by GenesisMauries** [comment]
:octocat: Los issues y milestone estan en el git hub de mi colaboradora. Disculpa por demorar en contestar, trabajare mas en familiarizarme con GitHub.

Gracias Alexandra.
